language: sass
script:
  - scss --sourcemap=none bulma/sass/keyster.scss public/css/bulma.min.css --style compressed
install:
  - nvm install 6.9.4
  - sudo apt-get install ruby-dev -y
  - gem install sass --no-user-install
  - npm list -g firebase-tools --depth=0 || npm install -g firebase-tools
  - cd functions && npm install && cd ..
after_success:
  - firebase deploy --token ${token}
cache:
  directories:
    - $(npm root -g)
    - $(npm config get prefix)/bin
