language: node_js
node_js:
  - "6.9.4"
script:
  - echo 'Hello Firebase'
install:
  - npm list -g firebase-tools --depth=0 || npm install -g firebase-tools
after_success:
  - firebase deploy --token ${token} --only database,hosting
cache:
  directories:
    - $(npm root -g)
    - $(npm config get prefix)/bin
