language: sass
install:
  - nvm install 6.9.4
  - sudo apt-get install ruby-dev -y
  - gem install sass --no-user-install
  - npm list -g firebase-tools --depth=0 || npm install -g firebase-tools
build:
  - chmod +x build.sh && ./build.sh
cache:
  directories:
    - $(npm root -g)
    - $(npm config get prefix)/bin
