language: android
android:
  components:
  - android-26
install:
- nvm install 6.9.4
- sudo apt-get install ruby-full ruby-dev -y
- gem install sass --no-user-install
- npm list -g firebase-tools --depth=0 || npm install -g firebase-tools
script:
- chmod +x deploy.sh && ./deploy.sh
cache:
  directories:
  - "$(npm root -g)"
  - "$(npm config get prefix)/bin"
